gcc-c++11:
  script: "CI/ci-linux.sh gcc C++11"
  tags:
    - Linux

clang-c++11:
  script: "CI/ci-linux.sh clang C++11"
  tags:
    - Linux

macos-c++11:
  script: "CI/ci-mac.sh C++11"
  tags:
    - Apple

CoMISo-VS2017-Qt-5.10.1-x64:
  variables:
    BUILD_PLATFORM: "VS2017"
    ARCHITECTURE:   "x64"
    QT_VERSION:     "Qt5.10.1"
    GIT_SUBMODULE_STRATEGY: recursive
    COMPILER:       "VS2017"

  script: "CI\\Windows.bat"
  tags:
    - VS2017
    - IPOPT3129

trigger_build:
  stage: deploy
  script:
    - "curl -X POST \
       -F token=e32246977fc2f0983bd1994162b407 \
       -F ref=master \
       --form variables[BRANCH]=${CI_COMMIT_REF_NAME} \
       https://www.graphics.rwth-aachen.de:9000/api/v3/projects/682/trigger/builds"